name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04, windows-2019]
        channel: [stable]  # TODO: add nightly
          - name: $ {{ matrix.name }}
            os: windows-2019
            channel: stable
            prepare_command: rustup default stable-msvc
    steps:
      - uses: actions/checkout@v2
      - if: matrix.channel == 'nightly'
        name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - if: matrix.channel == 'stable'
        run: rustup component add clippy
        # prepare
      - if: matrix.prepare_command != ''
        run: ${{ matrix.prepare_command }}
      - run: cargo check
      - if: matrix.channel == 'stable'
        run: cargo clippy
      - if: matrix.channel == 'nightly'
        run: cargo test -- --nocapture

  lint:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
